/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ds.spring.gradle;

import ds.spring.gradle.config.AppConfig;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    private static AnnotationConfigApplicationContext context;

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        context = new AnnotationConfigApplicationContext(AppConfig.class);
    }
}
